version: "3.9"

services:

  mysql:
    image: mariadb:latest
    container_name: funix_api_db
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - funix_api_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  mail:
    image: maildev/maildev
    container_name: funix_api_mail
    ports:
      - "1080:1080"
      - "1025:1025"

  funix-api:
    build:
      context: ../../../
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - mail
    container_name: funix_api
    volumes:
      - funix_api_db:/container/java
    hostname: funixapi
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    ports:
      - "8080:8080"

networks:
  default:
    name: funixprod_net_local
    external: true

volumes:
  funix_api_db:
