create table api_users
(
    id         bigint generated by default as identity primary key,
    created_at timestamp     not null,
    updated_at timestamp,
    uuid       varchar(255)  not null constraint UK_user_public_id unique,
    banned     boolean       not null,
    email      varchar(255)  not null,
    password   varchar(2000) not null,
    role       varchar(255)  not null,
    username   varchar(255)  not null constraint UK_user_username unique
);

create table api_users_tokens
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp     not null,
    updated_at      timestamp,
    uuid            varchar(255)  not null constraint UK_token_public_id unique,
    expiration_date timestamp,
    token           varchar(2000) not null constraint UK_api_token unique,
    user_id         bigint        not null constraint token_link_user references api_users
);

create table funixbot_commands
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    updated_at timestamp,
    uuid       varchar(255) not null constraint UK_command_public_id unique,
    command    varchar(30)  not null constraint UK_command_name unique,
    message    varchar(255) not null
);

create table funixbot_users_experience
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp    not null,
    updated_at        timestamp,
    uuid              varchar(255) not null constraint UK_fbot_user_public_id unique,
    last_message_date timestamp    not null,
    level             integer      not null,
    twitch_user_id    varchar(255) not null constraint UK_twitch_id_user unique,
    xp                integer      not null,
    xp_next_level     integer      not null
);

create table funix_api_mails
(
    id         bigint generated by default as identity primary key,
    created_at timestamp      not null,
    updated_at timestamp,
    uuid       varchar(255)   not null constraint UK_mail_id_public unique,
    from_mail  varchar(255)   not null,
    subject    varchar(255)   not null,
    text       varchar(10000) not null,
    to_mail    varchar(255)   not null,
    send       boolean        not null
);

create table twitch_client_tokens
(
    id                    bigint generated by default as identity primary key,
    created_at            timestamp(6) not null,
    updated_at            timestamp(6),
    uuid                  varchar(255) not null constraint twitch_client_tokens_public_id unique,
    access_token          varchar(255) not null constraint twitch_client_tokens_access_token unique,
    expiration_date_token timestamp(6) not null,
    o_auth_code           varchar(255) not null constraint twitch_client_tokens_oauth unique,
    refresh_token         varchar(255) not null constraint twitch_client_tokens_refresh unique,
    token_type            varchar(255) not null,
    twitch_user_id        varchar(255) not null,
    twitch_username       varchar(255) not null,
    user_id               bigint       not null constraint twitch_client_tokens_link_user references api_users
);
