apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: funixgaming-api-certificate
  namespace: "funixproductions-dev"
spec:
  secretName: funixgaming-api-certificate-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "dev.api.funixgaming.fr"
  dnsNames:
    - "dev.api.funixgaming.fr"
