version: "3.9"

services:

  mysql:
    image: postgres
    container_name: funix_api_db
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - funix_api_db:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "3306:5432"

  mail:
    image: maildev/maildev
    container_name: funix_api_mail
    ports:
      - "1080:1080"
      - "1025:1025"

  funix-api:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_started
      mail:
        condition: service_started
    container_name: funix-api
    volumes:
      - funix_api_app:/container/java
    hostname: funixapi
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TWITCH_APP_CLIENT_ID=${TWITCH_APP_CLIENT_ID}
      - TWITCH_APP_CLIENT_SECRET=${TWITCH_APP_CLIENT_SECRET}
    ports:
      - "8080:8080"

#Don't forget to create network in docker : docker network create funixprod_net_local
networks:
  default:
    name: funixprod_net_local
    external: true

volumes:
  funix_api_db:
  funix_api_app:
