create table if not exists funixbot_automessages
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp    not null,
    updated_at        timestamp,
    uuid              varchar(255) not null constraint UK_fbot_automessages_user_public_id unique,
    message           varchar(500) not null,
    game_name         varchar(100),
    is_announced      boolean      default false not null
);
