name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  docker-push-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push java funixapi
        run: |
          docker build -f prod.Dockerfile . --tag ghcr.io/funixproductions/funix-api:latest
          docker push ghcr.io/funixproductions/funix-api:latest
